### ISSUE TITLE
Проблема с пониманием

### ISSUE THREAD

**Issue by GigantPro** [mrzlkvvv/NSCMBot#1]
Доброво времени суток! У меня чтото не получается понять, ПОЧЕМУ ТЫ ПИДОР ЕБАНЫЙ ПИШЕШЬ ТГ БОТА НА GO БЛЯТЬ!??!

Заранее спасибо за ответ)

**Comment by GigantPro** [comment]
Э жи ез жи

**Comment by mrzlkvvv** [comment]
Добрый вечер. Старайся понять лучше. Успехов Вам в написании ботов на швайтоне

**Comment by GigantPro** [comment]
ВЫ ЛУЧШИЙ РАЗРАБОТЧИК
